import { prisma } from "@/lib/prisma";

export const SEED_THEMES = [
  {
    collection: "Kyoto Tea & Zen",
    themeJa: "和束の茶畑",
    themeEn: "Wazuka Tea Fields",
    verticalTextJa: "和束",
    subtitleEn: "WAZUKA / Kyoto Tea Fields",
    motif: "rolling green tea fields in Kyoto countryside, winding path, small tea shed, quiet rural landscape",
    colorPalette: "sage green, moss green, warm cream, charcoal",
    stylePreset: "Japandi Landscape",
  },
  {
    collection: "Kyoto Tea & Zen",
    themeJa: "茶の湯",
    themeEn: "Tea Ceremony",
    verticalTextJa: "茶の湯",
    subtitleEn: "TEA CEREMONY / The Art of Matcha",
    motif: "matcha bowl, bamboo whisk, iron kettle, tea scoop, tatami room, simple flower branch",
    colorPalette: "warm beige, muted green, dark wood, charcoal",
    stylePreset: "Tea Culture",
  },
  {
    collection: "Kyoto Tea & Zen",
    themeJa: "禅寺",
    themeEn: "Zen Temple",
    verticalTextJa: "禅景",
    subtitleEn: "ZEN SCENE / Japanese Temple Landscape",
    motif: "quiet Japanese temple, pine trees, stone steps, misty garden, reflective pond",
    colorPalette: "cream, pine green, grey stone, dusty red",
    stylePreset: "Zen Landscape",
  },
  {
    collection: "Showa Retro Japan",
    themeJa: "昭和路地",
    themeEn: "Showa Street",
    verticalTextJa: "昭和路地",
    subtitleEn: "SHOWA STREET / Retro Japan",
    motif: "retro Japanese alley, bicycle, noren curtain, old vending machine, warm afternoon light",
    colorPalette: "cream, indigo, terracotta, warm grey",
    stylePreset: "Showa Retro",
  },
  {
    collection: "Showa Retro Japan",
    themeJa: "喫茶店",
    themeEn: "Retro Kissaten",
    verticalTextJa: "喫茶店",
    subtitleEn: "KISSATEN / Japanese Coffee House",
    motif: "old Japanese coffee shop, wooden counter, glass window, coffee cup, nostalgic sign",
    colorPalette: "coffee brown, cream, faded red, charcoal",
    stylePreset: "Showa Retro",
  },
  {
    collection: "Japanese Original Landscape",
    themeJa: "山里",
    themeEn: "Mountain Village",
    verticalTextJa: "山里",
    subtitleEn: "MOUNTAIN VILLAGE / Rural Japan",
    motif: "quiet mountain village, old farmhouses, mist, small river, distant forest",
    colorPalette: "mist grey, moss green, warm beige, dark brown",
    stylePreset: "Countryside",
  },
  {
    collection: "Japanese Original Landscape",
    themeJa: "棚田",
    themeEn: "Rice Terraces",
    verticalTextJa: "棚田",
    subtitleEn: "RICE TERRACES / Japanese Countryside",
    motif: "Japanese rice terraces, sunset reflection, mountain silhouettes, rural path",
    colorPalette: "muted gold, olive green, cream, charcoal",
    stylePreset: "Countryside",
  },
  {
    collection: "Kyoto Tea & Zen",
    themeJa: "苔庭",
    themeEn: "Moss Garden",
    verticalTextJa: "苔庭",
    subtitleEn: "MOSS GARDEN / Kyoto Silence",
    motif: "moss garden, stone lantern, maple leaves, quiet temple corner",
    colorPalette: "moss green, stone grey, warm cream, deep brown",
    stylePreset: "Zen Landscape",
  },
  {
    collection: "Kyoto Tea & Zen",
    themeJa: "竹林",
    themeEn: "Bamboo Grove",
    verticalTextJa: "竹林",
    subtitleEn: "BAMBOO GROVE / Japanese Minimalism",
    motif: "bamboo forest path, soft light, minimal shadows, quiet atmosphere",
    colorPalette: "bamboo green, pale cream, soft grey, charcoal",
    stylePreset: "Japandi Landscape",
  },
  {
    collection: "Japandi Animals",
    themeJa: "鯉",
    themeEn: "Koi Fish",
    verticalTextJa: "鯉",
    subtitleEn: "KOI / Zen Water",
    motif: "koi fish swimming in circular ripples, minimal water pattern, Japanese print feeling",
    colorPalette: "deep green, ivory, orange red, charcoal",
    stylePreset: "Animal Japandi",
  },
  {
    collection: "Japandi Animals",
    themeJa: "狐",
    themeEn: "Fox",
    verticalTextJa: "狐",
    subtitleEn: "FOX / Forest Spirit",
    motif: "sleeping fox under autumn leaves, quiet forest floor, soft Japanese illustration",
    colorPalette: "rust orange, cream, moss green, charcoal",
    stylePreset: "Animal Japandi",
  },
  {
    collection: "Japandi Animals",
    themeJa: "鶴",
    themeEn: "Crane",
    verticalTextJa: "鶴",
    subtitleEn: "CRANE / Quiet Flight",
    motif: "Japanese cranes flying above misty water, minimal elegant composition",
    colorPalette: "ivory, charcoal, soft red, mist grey",
    stylePreset: "Animal Japandi",
  },
  {
    collection: "Japandi Animals",
    themeJa: "猫",
    themeEn: "Cat",
    verticalTextJa: "猫",
    subtitleEn: "CAT / Under the Willow",
    motif: "sleeping cat under a willow tree, minimal Japanese garden mood",
    colorPalette: "willow green, cream, soft grey, black",
    stylePreset: "Animal Japandi",
  },
  {
    collection: "Showa Retro Japan",
    themeJa: "赤いポスト",
    themeEn: "Red Postbox",
    verticalTextJa: "赤いポスト",
    subtitleEn: "RED POSTBOX / Old Japan",
    motif: "old red Japanese postbox on a quiet street, wooden houses, soft light",
    colorPalette: "faded red, cream, warm grey, muted green",
    stylePreset: "Showa Retro",
  },
  {
    collection: "Showa Retro Japan",
    themeJa: "駅前通り",
    themeEn: "Old Station Street",
    verticalTextJa: "駅前通り",
    subtitleEn: "OLD STATION STREET / Retro Japan",
    motif: "small Japanese station street, signs, bicycle, old storefronts, morning light",
    colorPalette: "cream, dusty blue, warm grey, faded red",
    stylePreset: "Showa Retro",
  },
  {
    collection: "Japanese Original Landscape",
    themeJa: "雪国",
    themeEn: "Snow Village",
    verticalTextJa: "雪国",
    subtitleEn: "SNOW VILLAGE / Quiet Japan",
    motif: "snow-covered Japanese village, warm window light, silent winter atmosphere",
    colorPalette: "snow white, pale blue, charcoal, warm amber",
    stylePreset: "Countryside",
  },
  {
    collection: "Japanese Original Landscape",
    themeJa: "港町",
    themeEn: "Fishing Town",
    verticalTextJa: "港町",
    subtitleEn: "FISHING TOWN / Coastal Japan",
    motif: "quiet Japanese fishing town, small boats, sea wall, morning haze",
    colorPalette: "sea blue, cream, weathered wood, grey",
    stylePreset: "Countryside",
  },
  {
    collection: "Kyoto Tea & Zen",
    themeJa: "石庭",
    themeEn: "Dry Garden",
    verticalTextJa: "石庭",
    subtitleEn: "DRY GARDEN / Zen Lines",
    motif: "zen dry garden, raked sand, stones, minimal shadows, temple wall",
    colorPalette: "sand beige, stone grey, charcoal, moss green",
    stylePreset: "Zen Landscape",
  },
  {
    collection: "Kyoto Tea & Zen",
    themeJa: "和菓子",
    themeEn: "Wagashi",
    verticalTextJa: "和菓子",
    subtitleEn: "WAGASHI / Sweet Tea Time",
    motif: "Japanese sweets with matcha, small ceramic plate, tea room setting",
    colorPalette: "matcha green, sakura pink, cream, dark wood",
    stylePreset: "Tea Culture",
  },
  {
    collection: "Japanese Original Landscape",
    themeJa: "夕暮れ",
    themeEn: "Japanese Dusk",
    verticalTextJa: "夕暮れ",
    subtitleEn: "DUSK / Quiet Japan",
    motif: "Japanese countryside at dusk, small road, distant mountains, soft glowing sky",
    colorPalette: "dusty orange, muted purple, cream, deep green",
    stylePreset: "Countryside",
  },
] as const;

export async function seedThemesIfEmpty(): Promise<void> {
  const count = await prisma.posterTheme.count();
  if (count > 0) return;

  for (const theme of SEED_THEMES) {
    await prisma.posterTheme.create({
      data: { ...theme, status: "idea" },
    });
  }
}
